### ISSUE TITLE
openerp_auto_run repository missing.. pls update.

### ISSUE THREAD

**Issue by johnbritto1** [camptocamp/buildout-odoo#37]
Getting distribution for 'mr.developer'.
Got mr.developer 1.34.
Getting distribution for 'zc.buildout==2.3.1'.
Got zc.buildout 2.3.1.
mr.developer: Creating missing sources dir /home/sodexis/instances/openerp-oca-runbot/src.
mr.developer: Queued 'openerp_auto_run' for checkout.
mr.developer: Queued 'scenarios' for checkout.
mr.developer: Queued 'templates' for checkout.
mr.developer: Cloned 'openerp_auto_run' with git.
mr.developer: git cloning of 'openerp_auto_run' failed.
mr.developer: ERROR: Repository not found.
mr.developer: fatal: Could not read from remote repository.
mr.developer: 
mr.developer: Please make sure you have the correct access rights
mr.developer: and the repository exists.
mr.developer: 
mr.developer: Cloned 'templates' with git.
mr.developer: git cloning of 'templates' failed.
mr.developer: ERROR: Repository not found.
mr.developer: fatal: Could not read from remote repository.
mr.developer: 
mr.developer: Please make sure you have the correct access rights
mr.developer: and the repository exists.
mr.developer: 
mr.developer: Cloned 'scenarios' with git.
mr.developer: There have been errors, see messages above.

**Comment by guewen** [comment]
Hello @johnbritto1 .

Sorry, this configuration file relies on our internal setup and then is not usable out of our internal setup.
